sudo: required
language: node_js
node_js:
  - "6.10.0"

addons:
  apt:
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

before_install:
  - cd ${TRAVIS_BUILD_DIR}

script:
  - node_modules/.bin/gulp travis
